version: "3"

services:
  server:
    container_name: server
    build:
      context: .
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT:-8000}"
    # Added Command for hot reloading in dev server
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
  
  postgres:
    image: postgres:12
    env_file: .env
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
