# Generated by Django 4.2.4 on 2023-08-15 07:43

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenseattypesmapping",
            name="seat_type",
            field=models.CharField(
                choices=[
                    ("PLATINUM", "Platinum"),
                    ("GOLD", "Gold"),
                    ("SILVER", "Silver"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="col",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="seat",
            name="raw",
            field=models.CharField(max_length=3),
        ),
    ]
